sudo: true

language: Haskell

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal

ghc: 7.8

before_install:
  - sudo apt-get install Haskell-Platform

install: 
- cabal install random-extras-0.19 
